(function () {
  var container=document.getElementById("live-matchups"),select=document.getElementById("week-select"),title=document.getElementById("matchups-week-title"),openMatchupKey=null;if(!container)return;
  var params=new URLSearchParams(window.location.search),linkedWeek=Number(params.get("week")||0);if(select&&linkedWeek>=1&&linkedWeek<=14){select.value=String(linkedWeek);select.dataset.userChanged="true";}
  var style=document.createElement("style");style.textContent=".matchup-record{margin-top:2px;color:#8ea6ba;font-size:.61rem;font-weight:800}.edge-wrap{margin-top:10px}.historical-note{text-align:center;color:#8ea6ba;font-size:.68rem;margin-top:8px}";document.head.appendChild(style);
  function normalizeName(n){var m={"#Numbers":"Burden Of Victory IIIx","Nabers Think I'm Sellin Dope":"The Bowers Rangers"};return m[n]||n||"Team";}
  function initials(n){return normalizeName(n).split(/\s+/).filter(Boolean).slice(0,2).map(function(w){return w[0].toUpperCase();}).join("");}
  function recordText(t){var r=t&&t.record?t.record:{};return Number(r.wins||0)+"-"+Number(r.losses||0)+(Number(r.ties||0)?"-"+Number(r.ties):"");}
  function makeTeamSide(team,teamData,historical){var side=document.createElement("div");side.className="matchup-team-side";var avatar=document.createElement("div");avatar.className="team-avatar";avatar.textContent=initials(team.teamName||team.name);var name=document.createElement("div");name.className="matchup-team-name";name.textContent=normalizeName(team.teamName||team.name);side.appendChild(avatar);side.appendChild(name);if(!historical){var record=document.createElement("div");record.className="matchup-record";record.textContent=recordText(teamData);side.appendChild(record);}var score=document.createElement("div");score.className="matchup-big-score";score.textContent=Number(team.score||team.totalPoints||0).toFixed(2);side.appendChild(score);if(!historical){var projection=document.createElement("div");projection.className="matchup-projection";projection.textContent="Proj. "+Number(team.projection||0).toFixed(2);side.appendChild(projection);}return side;}
  function predictionPct(h,a){var hp=Number(h.projection||0),ap=Number(a.projection||0);if(!hp&&!ap)return 50;var p=100/(1+Math.exp(-(hp-ap)/8));return Math.max(0,Math.min(100,p));}
  function makeProjectionBar(h,a){var hp=predictionPct(h,a),ap=100-hp,w=document.createElement("div");w.className="edge-wrap";w.innerHTML='<div class="edge-labels"><span>'+Math.round(hp)+'%</span><small>Projection Edge</small><span>'+Math.round(ap)+'%</span></div><div class="edge-bar"><span class="edge-segment edge-segment-home'+(hp>=ap?' favored':'')+'" style="width:'+hp+'%"></span><span class="edge-segment edge-segment-away'+(ap>hp?' favored':'')+'" style="width:'+ap+'%"></span><i class="edge-divider"></i></div>';return w;}
  function makeCard(matchup,teamMap,historical){var h=matchup.home||{},a=matchup.away||{},card=document.createElement("div");card.className="live-matchup-card";var teams=document.createElement("div");teams.className="matchup-faceoff";teams.appendChild(makeTeamSide(h,teamMap[String(h.teamId)],historical));var vs=document.createElement("div");vs.className="matchup-versus";vs.textContent="VS";teams.appendChild(vs);teams.appendChild(makeTeamSide(a,teamMap[String(a.teamId)],historical));card.appendChild(teams);if(!historical)card.appendChild(makeProjectionBar(h,a));return card;}
  async function json(path){var r=await fetch(path+"?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("unavailable");return r.json();}
  async function render(){try{var live=await json("data/live.json"),currentWeek=Number(live.week||live.scoringPeriod||1);if(select&&!select.dataset.userChanged)select.value=String(currentWeek);var requested=select?Number(select.value||currentWeek):currentWeek;if(title)title.textContent="Week "+requested;var teamMap={};(live.teams||[]).forEach(function(t){teamMap[String(t.id)]=t;});var source,historical=requested!==currentWeek;if(historical){if(requested===1){source=await json("data/matchups.json");}else{container.innerHTML='<div class="empty-week-card"><strong>Week '+requested+'</strong><span>Matchups will appear here when that week becomes available.</span></div>';return;}}else{source=live;try{var p=await json("data/live-projections.json"),pw=Number(p.week||p.scoringPeriod||0);if(pw===currentWeek&&p.projections)(source.matchups||[]).forEach(function(m){[m.home,m.away].forEach(function(s){var v=Number(p.projections[String(s.teamId)]);if(v>0)s.projection=v;});});}catch(e){}}
    container.innerHTML="";(source.matchups||[]).forEach(function(m){container.appendChild(makeCard(m,teamMap,historical));});if(historical){var note=document.createElement("div");note.className="historical-note";note.textContent="Final Week "+requested+" results";container.appendChild(note);}if(!(source.matchups||[]).length)container.innerHTML='<div class="app-loading">No matchups are available yet.</div>';
  }catch(e){container.innerHTML='<div class="app-loading">Matchup data is temporarily unavailable.</div>';}}
  if(select)select.addEventListener("change",function(){select.dataset.userChanged="true";openMatchupKey=null;history.replaceState(null,"","matchups.html?week="+select.value);render();});render();setInterval(render,10000);
})();