document.addEventListener("DOMContentLoaded", function () {
  var select=document.getElementById("team-select"),container=document.getElementById("rosters-live"),status=document.getElementById("roster-refresh-status"); if(!select||!container)return;
  document.querySelectorAll(".main-nav a").forEach(function(link){if(link.getAttribute("data-page")==="rosters")link.classList.add("active");});
  var lastSignature="",refreshInFlight=false,playerRanks={};
  function normalizeName(name){var map={"#Numbers":"Burden Of Victory IIIx","Nabers Think I'm Sellin Dope":"The Bowers Rangers"};return map[name]||name||"Team";}
  function slugify(name){return normalizeName(name).toLowerCase().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
  function positionClass(position){if(position==="D/ST")return "pos-dst";return "pos-"+String(position||"").toLowerCase().replace(/[^a-z]/g,"");}
  function starterSort(a,b){var order={"QB":0,"RB":1,"WR":2,"TE":3,"FLEX":4,"D/ST":5,"K":6},ao=Object.prototype.hasOwnProperty.call(order,a.slot)?order[a.slot]:99,bo=Object.prototype.hasOwnProperty.call(order,b.slot)?order[b.slot]:99;if(ao!==bo)return ao-bo;return String(a.name||"").localeCompare(String(b.name||""));}
  function playerScore(p){var s=Number(p&&p.actual);return Number.isFinite(s)?s:0;}
  function rosterSignature(teams){return teams.map(function(t){return String(t.id)+":"+(t.roster||[]).map(function(p){return String(p.id||p.playerId||"")+"@"+String(p.slot||"");}).join(",");}).join("|");}
  function rankLabel(player){var id=String(player.id||player.playerId||""),r=playerRanks[id];return r&&r.label?r.label:"";}
  function makePlayerRow(player,teamId){var row=document.createElement("div");row.className="player-row";row.setAttribute("data-player-id",String(player.id||player.playerId||""));row.setAttribute("data-team-id",String(teamId));var info=document.createElement("div");info.className="player-info";var name=document.createElement("span");name.className="team-name";var badge=document.createElement("span");badge.className="player-position "+positionClass(player.position);badge.textContent=player.position||"—";name.appendChild(badge);name.appendChild(document.createTextNode(player.name||"Unknown Player"));var rl=rankLabel(player);if(rl){var rank=document.createElement("span");rank.className="player-season-rank";rank.textContent=" "+rl;rank.style.cssText="margin-left:7px;color:#a9ea2d;font-size:.72rem;font-weight:900;white-space:nowrap";name.appendChild(rank);}var meta=document.createElement("span");meta.className="player-meta";meta.textContent=(player.proTeam||"")+" · "+(player.slot||"Bench");var points=document.createElement("span");points.className="player-points live-player-score";points.textContent=playerScore(player).toFixed(2);info.appendChild(name);info.appendChild(meta);row.appendChild(info);row.appendChild(points);return row;}
  function showSelectedRoster(){var selected=select.value;container.querySelectorAll(".roster").forEach(function(n){n.style.display=n.getAttribute("data-roster-key")===selected?"":"none";});try{sessionStorage.setItem("ags-selected-roster",selected);}catch(e){}}
  function buildRosters(teams){var previous=select.value;try{previous=previous||sessionStorage.getItem("ags-selected-roster")||"";}catch(e){}select.innerHTML="";container.innerHTML="";teams.forEach(function(team){var teamName=normalizeName(team.name||"Team "+team.id),key=slugify(teamName),option=document.createElement("option");option.value=key;option.textContent=teamName;select.appendChild(option);var roster=document.createElement("section");roster.className="roster";roster.setAttribute("data-roster-key",key);roster.setAttribute("data-team-id",String(team.id));roster.style.display="none";var st=document.createElement("h2");st.className="section-title";st.textContent="Starters";roster.appendChild(st);var starters=(team.roster||[]).filter(function(p){return p.slot!=="Bench"&&p.slot!=="IR";}).sort(starterSort),card=document.createElement("div");card.className="card";starters.forEach(function(p){card.appendChild(makePlayerRow(p,team.id));});var total=document.createElement("div");total.className="player-row team-total-score";total.innerHTML='<strong>Total</strong><strong class="live-team-total" data-team-id="'+String(team.id)+'">0.00</strong>';card.appendChild(total);roster.appendChild(card);var bt=document.createElement("h2");bt.className="section-title bench-title";bt.textContent="Bench / IR";roster.appendChild(bt);var bc=document.createElement("div");bc.className="card";(team.roster||[]).filter(function(p){return p.slot==="Bench"||p.slot==="IR";}).forEach(function(p){bc.appendChild(makePlayerRow(p,team.id));});roster.appendChild(bc);container.appendChild(roster);});if(previous&&Array.from(select.options).some(function(o){return o.value===previous;}))select.value=previous;else if(select.options.length)select.selectedIndex=0;select.onchange=showSelectedRoster;showSelectedRoster();}
  function updateScoresInPlace(teams){var byId={};teams.forEach(function(t){(t.roster||[]).forEach(function(p){byId[String(p.id||p.playerId||"")]=p;});});container.querySelectorAll(".player-row[data-player-id]").forEach(function(row){var p=byId[row.getAttribute("data-player-id")];if(!p)return;var el=row.querySelector(".live-player-score");if(el){var next=playerScore(p).toFixed(2);if(el.textContent!==next)el.textContent=next;}});teams.forEach(function(t){var el=container.querySelector('.live-team-total[data-team-id="'+String(t.id)+'"]');if(!el)return;var official=Number(t.actual),starters=(t.roster||[]).filter(function(p){return p.slot!=="Bench"&&p.slot!=="IR";}),calc=starters.reduce(function(sum,p){return sum+playerScore(p);},0),total=Number.isFinite(official)?official:calc,next=total.toFixed(2);if(el.textContent!==next)el.textContent=next;});}
  async function loadRanks(){try{var r=await fetch("data/player-ranks.json?ts="+Date.now(),{cache:"no-store"});if(r.ok){var d=await r.json();playerRanks=d.players||{};return true;}}catch(e){}return false;}
  async function refreshRosters(){if(refreshInFlight)return;refreshInFlight=true;try{await loadRanks();var response=await fetch("data/live.json?ts="+Date.now(),{cache:"no-store"});if(!response.ok)throw new Error("live roster data unavailable");var data=await response.json(),teams=Array.isArray(data.teams)?data.teams:[];if(!teams.length)throw new Error("no teams returned");var signature=rosterSignature(teams)+"|ranks:"+Object.keys(playerRanks).length;if(signature!==lastSignature){buildRosters(teams);lastSignature=signature;}updateScoresInPlace(teams);if(status)status.textContent="Live · updated "+new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit",second:"2-digit"});}catch(error){if(status)status.textContent="Live data temporarily unavailable";if(!lastSignature)container.innerHTML='<div class="app-loading">Roster data is temporarily unavailable.</div>';}finally{refreshInFlight=false;}}
  refreshRosters();setInterval(refreshRosters,10000);
});